import axios from 'axios';

const instance = axios.create({
    baseURL: 'http://hapi.spartan.ftd.com.br/api/'
});

const token = sessionStorage.getItem('access_token');

instance.defaults.headers.common['Authorization'] = 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImNiNTBhZDY3MDk1OWUyNmM1MGYwZjMzMzkyNGJkMTFhNGZhYzAyYzllZGVlNTExN2E3Y2E4NTlkZWE0NGRlNWU2NjM4Zjg1ZjNjMDMzMDc3In0.eyJhdWQiOiIyIiwianRpIjoiY2I1MGFkNjcwOTU5ZTI2YzUwZjBmMzMzOTI0YmQxMWE0ZmFjMDJjOWVkZWU1MTE3YTdjYTg1OWRlYTQ0ZGU1ZTY2MzhmODVmM2MwMzMwNzciLCJpYXQiOjE1MjI2NzY4MzgsIm5iZiI6MTUyMjY3NjgzOCwiZXhwIjoxNTIyNzYzMjM4LCJzdWIiOiIxMzM4Iiwic2NvcGVzIjpbXX0.nb4qXuM5yUuiWGnOEIPdmBreCVChg1KrN99NgUTi4Rwoqn2ASoY5VGsxb8bv9ZgM7M7PzNnj4NeKIJUv4Axsbmm0doaANi7ebecdjrRFTmlynQv15U5dtObowxbrpJgySgj5FiAdLYxU6NStQ7c3v7yUXYZ8j3lRBWt0OTX-JkdJtZvWBXrPJr9nL1jt5pTUg3WAdsnLUaLUbhIpZZSEIhqmVpIMejlivNCI9GYm17IaCW9NOYssdk_rpnuP-KuPPJxqCcqSkG2nYrZMATVLcgYzaj2tRUmhWOS8mS_rKVdL0Z0hMN2W_Ao3F-On4NLpjd1RuJl3weAJ9FbeBnPXvh-rfK_k6g8D4EepRy_89zpvoQvFxsX-kN-mEfE8w0fDVDQQpfx25gMesAmCQRNsW8-v5cpxLnjUaQbMZ7Lss1PfAw_oWI-r42QoQvRVFrvhcCJtrChSt78g6X1hodCd7oWp8R9zpoE9GtdKLDBqOGkiBD_MKN2vnOVdlFUXdpRUCkuai4SuIindmO58nuH5V5FsZNIGy3YIaUDwaKYOVkdG8dqJ0-TPCTgP5PBAOiPFRxrU04_RolSEr2JTc9eCXrHQyMLAiLLTgYbKwKPiIQdE2dBaA_Twgy48MANyPSjpf7meRqBigAw8oW1KIsnSDQTs-cb7WMDyRaahD-f7GpI';

export default instance;