export const CHAIN_CREATING = 'CHAIN_CREATING'
export const CHAIN_CREATE_SUCCESS = 'CHAIN_CREATE_SUCCESS'
export const CHAIN_CREATE_ERROR = 'CHAIN_CREATE_ERROR'

export const CHAIN_UPDATING = 'CHAIN_UPDATING'
export const CHAIN_UPDATE_SUCCESS = 'CHAIN_UPDATE_SUCCESS'
export const CHAIN_UPDATE_ERROR = 'CHAIN_UPDATE_ERROR'

export const CHAIN_LOAD_SUCCESS = 'CHAIN_REQUEST_SUCCESS'
export const CHAIN_LOADING = 'CHAIN_LOADING'
export const CHAIN_LOAD_ERROR = 'CHAIN_LOAD_ERROR'

export const CHAIN_REQUESTING = 'CHAIN_REQUESTING'
export const CHAIN_REQUEST_SUCCESS = 'CHAIN_REQUEST_SUCCESS'
export const CHAIN_REQUEST_ERROR = 'CHAIN_REQUEST_ERROR'

export const CHAIN_CURRENT_CLEAR = 'CHAIN_CURRENT_CLEAR'