export const CONGREGATION_CREATING = 'CONGREGATION_CREATING'
export const CONGREGATION_CREATE_SUCCESS = 'CONGREGATION_CREATE_SUCCESS'
export const CONGREGATION_CREATE_ERROR = 'CONGREGATION_CREATE_ERROR'

export const CONGREGATION_UPDATING = 'CONGREGATION_UPDATING'
export const CONGREGATION_UPDATE_SUCCESS = 'CONGREGATION_UPDATE_SUCCESS'
export const CONGREGATION_UPDATE_ERROR = 'CONGREGATION_UPDATE_ERROR'

export const CONGREGATION_LOAD_SUCCESS = 'CONGREGATION_REQUEST_SUCCESS'
export const CONGREGATION_LOADING = 'CONGREGATION_LOADING'
export const CONGREGATION_LOAD_ERROR = 'CONGREGATION_LOAD_ERROR'

export const CONGREGATION_REQUESTING = 'CONGREGATION_REQUESTING'
export const CONGREGATION_REQUEST_SUCCESS = 'CONGREGATION_REQUEST_SUCCESS'
export const CONGREGATION_REQUEST_ERROR = 'CONGREGATION_REQUEST_ERROR'

export const CONGREGATION_CURRENT_CLEAR = 'CONGREGATION_CURRENT_CLEAR'