export const DISCIPLINE_CREATING = 'DISCIPLINE_CREATING'
export const DISCIPLINE_CREATE_SUCCESS = 'DISCIPLINE_CREATE_SUCCESS'
export const DISCIPLINE_CREATE_ERROR = 'DISCIPLINE_CREATE_ERROR'

export const DISCIPLINE_UPDATING = 'DISCIPLINE_UPDATING'
export const DISCIPLINE_UPDATE_SUCCESS = 'DISCIPLINE_UPDATE_SUCCESS'
export const DISCIPLINE_UPDATE_ERROR = 'DISCIPLINE_UPDATE_ERROR'

export const DISCIPLINE_LOAD_SUCCESS = 'DISCIPLINE_REQUEST_SUCCESS'
export const DISCIPLINE_LOADING = 'DISCIPLINE_LOADING'
export const DISCIPLINE_LOAD_ERROR = 'DISCIPLINE_LOAD_ERROR'

export const DISCIPLINE_REQUESTING = 'DISCIPLINE_REQUESTING'
export const DISCIPLINE_REQUEST_SUCCESS = 'DISCIPLINE_REQUEST_SUCCESS'
export const DISCIPLINE_REQUEST_ERROR = 'DISCIPLINE_REQUEST_ERROR'

export const DISCIPLINE_CURRENT_CLEAR = 'DISCIPLINE_CURRENT_CLEAR'