// export const CONTRIBUTORS_SET = 'CONTRIBUTORS_SET'
// export const CONTRIBUTORS_ERROR = 'CONTRIBUTORS_ERROR'

export const INDICATORS_REQUESTING = 'INDICATORS_REQUESTING'
export const INDICATORS_REQUEST_SUCCESS = 'INDICATORS_REQUEST_SUCCESS'
export const INDICATORS_REQUEST_ERROR = 'INDICATORS_REQUEST_ERROR'