export const JOB_TITLE_CREATING = 'JOB_TITLE_CREATING'
export const JOB_TITLE_CREATE_SUCCESS = 'JOB_TITLE_CREATE_SUCCESS'
export const JOB_TITLE_CREATE_ERROR = 'JOB_TITLE_CREATE_ERROR'

export const JOB_TITLE_UPDATING = 'JOB_TITLE_UPDATING'
export const JOB_TITLE_UPDATE_SUCCESS = 'JOB_TITLE_UPDATE_SUCCESS'
export const JOB_TITLE_UPDATE_ERROR = 'JOB_TITLE_UPDATE_ERROR'

export const JOB_TITLE_LOAD_SUCCESS = 'JOB_TITLE_REQUEST_SUCCESS'
export const JOB_TITLE_LOADING = 'JOB_TITLE_LOADING'
export const JOB_TITLE_LOAD_ERROR = 'JOB_TITLE_LOAD_ERROR'

export const JOB_TITLE_REQUESTING = 'JOB_TITLE_REQUESTING'
export const JOB_TITLE_REQUEST_SUCCESS = 'JOB_TITLE_REQUEST_SUCCESS'
export const JOB_TITLE_REQUEST_ERROR = 'JOB_TITLE_REQUEST_ERROR'

export const JOB_TITLE_CURRENT_CLEAR = 'JOB_TITLE_CURRENT_CLEAR'
export const UNLOAD_JOB_TITLE = 'UNLOAD_JOB_TITLE'