export const LEVEL_CREATING = 'LEVEL_CREATING'
export const LEVEL_CREATE_SUCCESS = 'LEVEL_CREATE_SUCCESS'
export const LEVEL_CREATE_ERROR = 'LEVEL_CREATE_ERROR'

export const LEVEL_UPDATING = 'LEVEL_UPDATING'
export const LEVEL_UPDATE_SUCCESS = 'LEVEL_UPDATE_SUCCESS'
export const LEVEL_UPDATE_ERROR = 'LEVEL_UPDATE_ERROR'

export const LEVEL_LOAD_SUCCESS = 'LEVEL_REQUEST_SUCCESS'
export const LEVEL_LOADING = 'LEVEL_LOADING'
export const LEVEL_LOAD_ERROR = 'LEVEL_LOAD_ERROR'

export const LEVEL_REQUESTING = 'LEVEL_REQUESTING'
export const LEVEL_REQUEST_SUCCESS = 'LEVEL_REQUEST_SUCCESS'
export const LEVEL_REQUEST_ERROR = 'LEVEL_REQUEST_ERROR'

export const LEVEL_CURRENT_CLEAR = 'LEVEL_CURRENT_CLEAR'