export const LOCALIZATION_CREATING = 'LOCALIZATION_CREATING'
export const LOCALIZATION_CREATE_SUCCESS = 'LOCALIZATION_CREATE_SUCCESS'
export const LOCALIZATION_CREATE_ERROR = 'LOCALIZATION_CREATE_ERROR'

export const LOCALIZATION_UPDATING = 'LOCALIZATION_UPDATING'
export const LOCALIZATION_UPDATE_SUCCESS = 'LOCALIZATION_UPDATE_SUCCESS'
export const LOCALIZATION_UPDATE_ERROR = 'LOCALIZATION_UPDATE_ERROR'

export const LOCALIZATION_LOAD_SUCCESS = 'LOCALIZATION_REQUEST_SUCCESS'
export const LOCALIZATION_LOADING = 'LOCALIZATION_LOADING'
export const LOCALIZATION_LOAD_ERROR = 'LOCALIZATION_LOAD_ERROR'

export const LOCALIZATION_REQUESTING = 'LOCALIZATION_REQUESTING'
export const LOCALIZATION_REQUEST_SUCCESS = 'LOCALIZATION_REQUEST_SUCCESS'
export const LOCALIZATION_REQUEST_ERROR = 'LOCALIZATION_REQUEST_ERROR'
