export const PROFILE_CREATING = 'PROFILE_CREATING'
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS'
export const PROFILE_CREATE_ERROR = 'PROFILE_CREATE_ERROR'

export const PROFILE_UPDATING = 'PROFILE_UPDATING'
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR'

export const PROFILE_LOAD_SUCCESS = 'PROFILE_REQUEST_SUCCESS'
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_LOAD_ERROR = 'PROFILE_LOAD_ERROR'

export const PROFILE_REQUESTING = 'PROFILE_REQUESTING'
export const PROFILE_REQUEST_SUCCESS = 'PROFILE_REQUEST_SUCCESS'
export const PROFILE_REQUEST_ERROR = 'PROFILE_REQUEST_ERROR'

export const PROFILE_CURRENT_CLEAR = 'PROFILE_CURRENT_CLEAR'