export const ROLE_CREATING = 'ROLE_CREATING'
export const ROLE_CREATE_SUCCESS = 'ROLE_CREATE_SUCCESS'
export const ROLE_CREATE_ERROR = 'ROLE_CREATE_ERROR'

export const ROLE_UPDATING = 'ROLE_UPDATING'
export const ROLE_UPDATE_SUCCESS = 'ROLE_UPDATE_SUCCESS'
export const ROLE_UPDATE_ERROR = 'ROLE_UPDATE_ERROR'

export const ROLE_LOAD_SUCCESS = 'ROLE_REQUEST_SUCCESS'
export const ROLE_LOADING = 'ROLE_LOADING'
export const ROLE_LOAD_ERROR = 'ROLE_LOAD_ERROR'

export const ROLE_REQUESTING = 'ROLE_REQUESTING'
export const ROLE_REQUEST_SUCCESS = 'ROLE_REQUEST_SUCCESS'
export const ROLE_REQUEST_ERROR = 'ROLE_REQUEST_ERROR'
