export const RULE_CREATING = 'RULE_CREATING'
export const RULE_CREATE_SUCCESS = 'RULE_CREATE_SUCCESS'
export const RULE_CREATE_ERROR = 'RULE_CREATE_ERROR'

export const RULE_UPDATING = 'RULE_UPDATING'
export const RULE_UPDATE_SUCCESS = 'RULE_UPDATE_SUCCESS'
export const RULE_UPDATE_ERROR = 'RULE_UPDATE_ERROR'

export const RULE_LOAD_SUCCESS = 'RULE_REQUEST_SUCCESS'
export const RULE_LOADING = 'RULE_LOADING'
export const RULE_LOAD_ERROR = 'RULE_LOAD_ERROR'

export const RULE_REQUESTING = 'RULE_REQUESTING'
export const RULE_REQUEST_SUCCESS = 'RULE_REQUEST_SUCCESS'
export const RULE_REQUEST_ERROR = 'RULE_REQUEST_ERROR'
