export const SCHOOL_TYPES_CREATING = 'SCHOOL_TYPES_CREATING'
export const SCHOOL_TYPES_CREATE_SUCCESS = 'SCHOOL_TYPES_CREATE_SUCCESS'
export const SCHOOL_TYPES_CREATE_ERROR = 'SCHOOL_TYPES_CREATE_ERROR'

export const SCHOOL_TYPES_UPDATING = 'SCHOOL_TYPES_UPDATING'
export const SCHOOL_TYPES_UPDATE_SUCCESS = 'SCHOOL_TYPES_UPDATE_SUCCESS'
export const SCHOOL_TYPES_UPDATE_ERROR = 'SCHOOL_TYPES_UPDATE_ERROR'

export const SCHOOL_TYPES_LOAD_SUCCESS = 'SCHOOL_TYPES_REQUEST_SUCCESS'
export const SCHOOL_TYPES_LOADING = 'SCHOOL_TYPES_LOADING'
export const SCHOOL_TYPES_LOAD_ERROR = 'SCHOOL_TYPES_LOAD_ERROR'

export const SCHOOL_TYPES_REQUESTING = 'SCHOOL_TYPES_REQUESTING'
export const SCHOOL_TYPES_REQUEST_SUCCESS = 'SCHOOL_TYPES_REQUEST_SUCCESS'
export const SCHOOL_TYPES_REQUEST_ERROR = 'SCHOOL_TYPES_REQUEST_ERROR'
