export const SECTOR_CREATING = 'SECTOR_CREATING'
export const SECTOR_CREATE_SUCCESS = 'SECTOR_CREATE_SUCCESS'
export const SECTOR_CREATE_ERROR = 'SECTOR_CREATE_ERROR'

export const SECTOR_UPDATING = 'SECTOR_UPDATING'
export const SECTOR_UPDATE_SUCCESS = 'SECTOR_UPDATE_SUCCESS'
export const SECTOR_UPDATE_ERROR = 'SECTOR_UPDATE_ERROR'

export const SECTOR_LOAD_SUCCESS = 'SECTOR_REQUEST_SUCCESS'
export const SECTOR_LOADING = 'SECTOR_LOADING'
export const SECTOR_LOAD_ERROR = 'SECTOR_LOAD_ERROR'

export const SECTOR_REQUESTING = 'SECTOR_REQUESTING'
export const SECTOR_REQUEST_SUCCESS = 'SECTOR_REQUEST_SUCCESS'
export const SECTOR_REQUEST_ERROR = 'SECTOR_REQUEST_ERROR'

export const SECTOR_CURRENT_CLEAR = 'SECTOR_CURRENT_CLEAR'