export const SHIFT_CREATING = 'SHIFT_CREATING'
export const SHIFT_CREATE_SUCCESS = 'SHIFT_CREATE_SUCCESS'
export const SHIFT_CREATE_ERROR = 'SHIFT_CREATE_ERROR'

export const SHIFT_UPDATING = 'SHIFT_UPDATING'
export const SHIFT_UPDATE_SUCCESS = 'SHIFT_UPDATE_SUCCESS'
export const SHIFT_UPDATE_ERROR = 'SHIFT_UPDATE_ERROR'

export const SHIFT_LOAD_SUCCESS = 'SHIFT_REQUEST_SUCCESS'
export const SHIFT_LOADING = 'SHIFT_LOADING'
export const SHIFT_LOAD_ERROR = 'SHIFT_LOAD_ERROR'

export const SHIFT_REQUESTING = 'SHIFT_REQUESTING'
export const SHIFT_REQUEST_SUCCESS = 'SHIFT_REQUEST_SUCCESS'
export const SHIFT_REQUEST_ERROR = 'SHIFT_REQUEST_ERROR'
export const SHIFT_UNLOAD = 'SHIFT_UNLOAD'