export const SHIFT_CREATING = 'SHIFT_CREATING'
export const SHIFT_CREATE_SUCCESS = 'SHIFT_CREATE_SUCCESS'
export const SHIFT_CREATE_ERROR = 'SHIFT_CREATE_ERROR'

export const SHIFT_REQUESTING = 'SHIFT_REQUESTING'
export const SHIFT_REQUEST_SUCCESS = 'SHIFT_REQUEST_SUCCESS'
export const SHIFT_REQUEST_ERROR = 'SHIFT_REQUEST_ERROR'
