export const STUDENTS_CREATING = 'STUDENTS_CREATING';
export const STUDENTS_CREATE_SUCCESS = 'STUDENTS_CREATE_SUCCESS';
export const STUDENTS_CREATE_ERROR = 'STUDENTS_CREATE_ERROR';

export const STUDENTS_REQUESTING = 'STUDENTS_REQUESTING';
export const STUDENTS_REQUEST_SUCCESS = 'STUDENTS_REQUEST_SUCCESS';
export const STUDENTS_REQUEST_ERROR = 'STUDENTS_REQUEST_ERROR';

export const STUDENTS_SELECT_LEVEL = 'STUDENTS_SELECT_LEVEL';
export const STUDENTS_SET_LEVEL = 'STUDENTS_SET_LEVEL';

export const STUDENTS_SELECT_SHIFT = 'STUDENTS_SELECT_SHIFT';
export const STUDENTS_SET_SHIFT = 'STUDENTS_SET_SHIFT';

export const UNLOAD_STUDENTS = 'UNLOAD_STUDENTS';
