export const STUDENTS_CREATING = 'STUDENTS_CREATING';
export const STUDENTS_CREATE_SUCCESS = 'STUDENTS_CREATE_SUCCESS';
export const STUDENTS_CREATE_ERROR = 'STUDENTS_CREATE_ERROR';

export const STUDENTS_REQUESTING = 'STUDENTS_REQUESTING';
export const STUDENTS_REQUEST_SUCCESS = 'STUDENTS_REQUEST_SUCCESS';
export const STUDENTS_REQUEST_ERROR = 'STUDENTS_REQUEST_ERROR';
