export const SUBSIDIARY_CREATING = 'SUBSIDIARY_CREATING'
export const SUBSIDIARY_CREATE_SUCCESS = 'SUBSIDIARY_CREATE_SUCCESS'
export const SUBSIDIARY_CREATE_ERROR = 'SUBSIDIARY_CREATE_ERROR'

export const SUBSIDIARY_UPDATING = 'SUBSIDIARY_UPDATING'
export const SUBSIDIARY_UPDATE_SUCCESS = 'SUBSIDIARY_UPDATE_SUCCESS'
export const SUBSIDIARY_UPDATE_ERROR = 'SUBSIDIARY_UPDATE_ERROR'

export const SUBSIDIARY_LOAD_SUCCESS = 'SUBSIDIARY_REQUEST_SUCCESS'
export const SUBSIDIARY_LOADING = 'SUBSIDIARY_LOADING'
export const SUBSIDIARY_LOAD_ERROR = 'SUBSIDIARY_LOAD_ERROR'

export const SUBSIDIARY_REQUESTING = 'SUBSIDIARY_REQUESTING'
export const SUBSIDIARY_REQUEST_SUCCESS = 'SUBSIDIARY_REQUEST_SUCCESS'
export const SUBSIDIARY_REQUEST_ERROR = 'SUBSIDIARY_REQUEST_ERROR'

export const SUBSIDIARY_CURRENT_CLEAR = 'SUBSIDIARY_CURRENT_CLEAR'