const routes = {
  '/': 'Home',
  '/login': 'Login',
  '/logout': 'Logout',
  '/dashboard': 'Dashboard',
  '/carteira': 'Carteira',
  '/carteira/escolas': 'Escolas',
  '/carteira/escolas/form': 'Cadastro',
  '/cadastro': 'Cadastro',
  '/cadastro/cargos': 'Cargos',
  '/cadastro/cargos/form': 'Cargos',
  '/cadastro/filiais': 'Filiais',
  '/cadastro/filiais/form': 'Filiais',
  '/cadastro/setores': 'Setores',
  '/cadastro/setores/form': 'Setores',
  '/cadastro/disciplinas': 'Disciplinas',
  '/cadastro/disciplinas/form': 'Disciplinas',
  '/cadastro/tipos-localizacao': 'Tipos de Localizaçāo',
  '/cadastro/tipos-localizacao/form': 'Tipos de Localizaçāo',
  '/cadastro/congregacoes': 'Congregações',
  '/cadastro/congregacoes/form': 'Congregações',
  '/cadastro/perfis': 'Perfis',
  '/cadastro/perfis/form': 'Perfis',
  '/cadastro/redes': 'Redes',
  '/cadastro/redes/form': 'Redes'      
};
export default routes;
